// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"
import "calculate_tax"
import "card"
import "preview"
import "display_text"
import "chartkick"
import "Chart.bundle"
import "scroll_down"
